Repository BabTubeProject/BabTube, pull requests merged in 2023-09, with the labels that each got.

#8 Feat: 로그인화면 UI구현
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/LoginViewController/LoginViewController.swift
  BabTube/BabTube/SceneDelegate.swift
Labels: UI

#15 [REFACTOR] MainColor 변경 & MyPage 로고 크기 변경, TableView 스크롤 없애기
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
  BabTube/BabTube/Util/Color.swift
Labels: REFACTOR

#13 FEAT: Main화면 UI구성
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Assets.xcassets/MainLogo.imageset/Contents.json
  BabTube/BabTube/Assets.xcassets/MainLogo.imageset/MainLogo.png
  BabTube/BabTube/MainViewContoller/MainCollectionView.swift
  BabTube/BabTube/MainViewContoller/MainCollectionViewCell.swift
  BabTube/BabTube/MainViewContoller/MainTableHeader.swift
  BabTube/BabTube/MainViewContoller/MainTableViewCell.swift
  BabTube/BabTube/MainViewContoller/MainViewController.swift
  BabTube/BabTube/MainViewContoller/header.swift
Labels: UI

#19 Issue#3 LikeView UI 구현
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Assets.xcassets/LikeImage1.imageset/Contents.json
  BabTube/BabTube/Assets.xcassets/LikeImage1.imageset/다운로드.jpeg
  BabTube/BabTube/Assets.xcassets/LikeImage2.imageset/Contents.json
  BabTube/BabTube/Assets.xcassets/LikeImage2.imageset/images.jpeg
  BabTube/BabTube/Assets.xcassets/LikeViewImage.imageset/BabTube 로고 2.png
  BabTube/BabTube/Assets.xcassets/LikeViewImage.imageset/Contents.json
  BabTube/BabTube/LikeViewController/DetailLikeTableViewCell.swift
  BabTube/BabTube/LikeViewController/LikeViewController.swift
Labels: UI

#12 FEAT: VideoDetail 화면 UI 구성
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Util/Reuseable.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
  BabTube/BabTube/VideoDetailViewController/View/CommentStackView.swift
  BabTube/BabTube/VideoDetailViewController/View/CommentTableViewCell.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionTableViewCell.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionVerticalStackView.swift
Labels: UI

#21 FEAT: Youtube Search API 가져오기
  .gitignore
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Model/SearchData.swift
  BabTube/BabTube/Util/APIHandler.swift
  BabTube/BabTube/Util/NetworkError.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
Labels: FEATURE

#25 Issue#7 로그인을 위한 정보 저장 기능, 좋아요 표시한 동영상 정보 저장 기능 추가
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/LoginViewController/UserDaTa.swift
  BabTube/BabTube/LoginViewController/UserDataManager.swift
  BabTube/BabTube/Model/UserData.swift
  BabTube/BabTube/Model/UserDataManager.swift
Labels: FEATURE

#29 FEAT: VideoDetail 화면 API 연결
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Model/SearchData.swift
  BabTube/BabTube/Model/VideoData.swift
  BabTube/BabTube/Util/APIHandler.swift
  BabTube/BabTube/Util/ImageLoader.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionTableViewCell.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionVerticalStackView.swift
Labels: FEATURE

#34 Issue#31 UserData 시청기록 추가, 자기소개 삭제
  BabTube/BabTube/Model/UserData.swift
  BabTube/BabTube/Model/UserDataManager.swift
Labels: FEATURE

#40 FEAT: 로그인/회원가입 버튼 UI 수정
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/LoginViewController/LoginViewController.swift
  BabTube/BabTube/LoginViewController/MembershipViewController.swift
Labels: UI

#43 Issue#39
  BabTube/BabTube/LikeViewController/DetailLikeTableViewCell.swift
  BabTube/BabTube/LikeViewController/LikeViewController.swift
Labels: FEATURE, UI

#42 Issue#26 회원가입으로 유저정보를 UserDefaults에 저장하는 기능
  BabTube/BabTube/LoginViewController/MembershipViewController.swift
  BabTube/BabTube/LoginViewController/ProfileMakeViewController.swift
  BabTube/BabTube/Model/UserDataManager.swift
Labels: FEATURE

#44 FEAT: VideoDetail 화면에서 이미지를 보여주는 부분을 영상으로 변경
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Info.plist
  BabTube/BabTube/MainViewContoller/MainViewController.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
Labels: FEATURE, UI

#49 Issue#24
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/RecordCollectionViewCell.swift
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/RecordTableViewCell.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
Labels: FEATURE

#51 Issue#48 프로필페이지 자기소개 UI 제거
  BabTube/BabTube/LoginViewController/ProfileMakeViewController.swift
Labels: UI

#52 feat: 비디오 디테일 화면 ui 변경
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Util/Date.swift
  BabTube/BabTube/Util/String.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
  BabTube/BabTube/VideoDetailViewController/View/AddCommentStackView.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionTableViewCell.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionVerticalStackView.swift
Labels: FEATURE, UI

#55 FEAT: 댓글 기능 추가 + 로그아웃후 다시 회원가입 버튼 클릭시 이동이 안되는 버그 수정
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Model/CommentManager.swift
  BabTube/BabTube/Model/VideoComment.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
  BabTube/BabTube/VideoDetailViewController/View/AddCommentStackView.swift
  BabTube/BabTube/VideoDetailViewController/View/CommentTableViewCell.swift
Labels: FEATURE, UI

#57 Issue#50
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/LoginViewController/ProfileMakeViewController.swift
  BabTube/BabTube/Model/UserDataManager.swift
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/ProfileTableViewCell.swift
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/QuitTableViewCell.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
Labels: FEATURE

#59 Feat: 메인페이지에 API 연결하기 (썸네일만 표시)
  BabTube/BabTube/MainViewContoller/MainCollectionViewCell.swift
  BabTube/BabTube/MainViewContoller/MainTableViewCell.swift
  BabTube/BabTube/MainViewContoller/MainViewController.swift
Labels: FEATURE

#61 [FEAT] LikeView에서 VideoId 넘겨줌
  BabTube/BabTube/LikeViewController/LikeViewController.swift
Labels: FEATURE

#56 BUG: Profile 이미지가 사각형으로 나오는 버그 & 댓글이 많을경우 짤려서 보이는 버그 해결
  BabTube/BabTube.xcodeproj/project.pbxproj
  BabTube/BabTube/Util/UITextView.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
  BabTube/BabTube/VideoDetailViewController/View/AddCommentStackView.swift
  BabTube/BabTube/VideoDetailViewController/View/CommentTableViewCell.swift
Labels: BUG

#63 Issue#58
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/RecordCollectionViewCell.swift
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/RecordTableViewCell.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
Labels: FEATURE

#64 FIX: viewHistory를 loginUser의 viewHistory로 변경
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
Labels: REFACTOR

#67 FEATURE: 좋아요 페이지 연결 데이터를 LikeVideo로 변경
  BabTube/BabTube/LikeViewController/DetailLikeTableViewCell.swift
  BabTube/BabTube/LikeViewController/LikeViewController.swift
  BabTube/BabTube/Model/UserData.swift
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/RecordTableViewCell.swift
Labels: FEATURE

#70 FEAT: 좋아요 페이지에 좋아요한 영상이 보이도록 구현 & 탈퇴 버튼 클릭시 로그인 되어있는 유저만 삭제되도록 변경
  BabTube/BabTube/LikeViewController/LikeViewController.swift
  BabTube/BabTube/Model/UserData.swift
  BabTube/BabTube/Model/UserDataManager.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionVerticalStackView.swift
Labels: FEATURE, REFACTOR

#71 BUG,FIX: API를 못가져 오는 버그 수정, 좋아요 누르고 다시 비디오 접근시 좋아요가 되도록 변경
  BabTube/BabTube/LikeViewController/DetailLikeTableViewCell.swift
  BabTube/BabTube/LikeViewController/LikeViewController.swift
  BabTube/BabTube/Model/UserDataManager.swift
  BabTube/BabTube/Model/VideoData.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
  BabTube/BabTube/Util/APIHandler.swift
  BabTube/BabTube/VideoDetailViewController/VideoDetailViewController.swift
  BabTube/BabTube/VideoDetailViewController/View/VideoDescriptionVerticalStackView.swift
Labels: BUG

#72 BUG: 좋아요리스트가 안보이는 버그 수정&같은 비디오가 시청기록에 쌓이는 버그 수정
  BabTube/BabTube/LikeViewController/DetailLikeTableViewCell.swift
  BabTube/BabTube/LikeViewController/LikeViewController.swift
  BabTube/BabTube/MainViewContoller/MainTableViewCell.swift
  BabTube/BabTube/MainViewContoller/MainViewController.swift
  BabTube/BabTube/Model/UserData.swift
  BabTube/BabTube/Model/UserDataManager.swift
  BabTube/BabTube/MyPageViewController/MyPageTableViewCell/RecordTableViewCell.swift
  BabTube/BabTube/MyPageViewController/MyPageViewController.swift
Labels: BUG

#75 FIX: 좋아요 페이지 Cell을 이상하게 그리는 버그 수정
  BabTube/BabTube/LikeViewController/DetailLikeTableViewCell.swift
  BabTube/BabTube/LikeViewController/LikeViewController.swift
  BabTube/BabTube/MainViewContoller/MainTableViewCell.swift
Labels: BUG

#76 Issue#68
  BabTube/BabTube/LikeViewController/DetailLikeTableViewCell.swift
  BabTube/BabTube/LikeViewController/LikeViewController.swift
  BabTube/BabTube/MainViewContoller/MainTableViewCell.swift
  BabTube/BabTube/MainViewContoller/MainViewController.swift
  BabTube/BabTube/Util/Font.swift
Labels: UI, REFACTOR

#81 fix: 회원가입 후 다시 회원가입 버튼 클릭시 화면 이동이 안되는 버그
  BabTube/BabTube/LoginViewController/MembershipViewController.swift
  BabTube/BabTube/LoginViewController/ProfileMakeViewController.swift
Labels: BUG

#82 FEATURE: 키보드 레이아웃 추가
  BabTube/BabTube/LoginViewController/LoginViewController.swift
  BabTube/BabTube/LoginViewController/MembershipViewController.swift
  BabTube/BabTube/LoginViewController/ProfileMakeViewController.swift
Labels: FEATURE, UI
